new function 'create' for creating new ADS
htmlacademy-javascript/1808687-keksobooking-23 pull request #3
Opened 2021-06-19 17:52 UTC by Akame320

Только я там забыл console.log() удалить(( В браузер пошел проверять объект. Как проверил сразу запушил(((

2021-06-19 17:54 UTC, Akame320 commented
И еще Eslint ругается на конкатенацию в тернарном операторе. Думаю это не сильно страшно?

2021-06-20 11:36 UTC, dtsaryov commented
> Только я там забыл console.log() удалить(( В браузер пошел проверять объект. Как проверил сразу запушил(((

Ну так коммиты бесплатные. Если нужно поправить - поправь

2021-06-20 11:36 UTC, dtsaryov commented
> И еще Eslint ругается на конкатенацию в тернарном операторе. Думаю это не сильно страшно?

Сильно страшно

2021-06-20 11:58 UTC, dtsaryov requested changes

2021-06-20 11:58 UTC, dtsaryov commented on index.html
> +<!--  <script src="js/Ads.js"></script>-->
Удалить

2021-06-20 11:58 UTC, dtsaryov commented on js/main.js
> +  const photos = ['https://assets.htmlacademy.ru/content/intensive/javascript-1/keksobooking/duonguyen-8LrGtIxxa4w.jpg', 'https://assets.htmlacademy.ru/content/intensive/javascript-1/keksobooking/bra
[Б7. Названия констант (постоянных значений) написаны прописными (заглавными) буквами.](https://up.htmlacademy.ru/javascript/23/criteries#b7)

2021-06-20 11:58 UTC, dtsaryov commented on js/main.js
> +  const photos = ['https://assets.htmlacademy.ru/content/intensive/javascript-1/keksobooking/duonguyen-8LrGtIxxa4w.jpg', 'https://assets.htmlacademy.ru/content/intensive/javascript-1/keksobooking/bra
[Б10. Список констант идёт перед основным кодом.](https://up.htmlacademy.ru/javascript/23/criteries#b10)

2021-06-20 11:58 UTC, dtsaryov commented on js/main.js
> +  const photos = ['https://assets.htmlacademy.ru/content/intensive/javascript-1/keksobooking/duonguyen-8LrGtIxxa4w.jpg', 'https://assets.htmlacademy.ru/content/intensive/javascript-1/keksobooking/bra
[Д20. Константы, используемые внутри функций, создаются вне функций и используются повторно через замыкания.](https://up.htmlacademy.ru/javascript/23/criteries#d20)

2021-06-20 11:58 UTC, dtsaryov commented on js/main.js
> +function createAds(){
Вызовы функций выше во-первых бесполезные, ибо не используются, а во-вторых, идут между объявлениями функций, что тоже неправильно.

Все реальные вызовы должны идти после всех объявлений

2021-06-20 11:58 UTC, dtsaryov commented on js/main.js
> +  function getAvatar(){
Ни в коем случае не объявляй функции внутри функций (только если без этого никак не обойтись) - профита никакого, но усложняет чтение и понимание кода

2021-06-20 11:58 UTC, dtsaryov commented on js/main.js
> +  const typesCheckout = ['12:00', '13:00', '14:00'];
нет смысла два раза хранить одно и то же

2021-06-20 11:58 UTC, dtsaryov commented on js/main.js
> +    }
Просто при объявляй поле avatar в нужном месте и вызови генерацию случайного числа, обернув в новую функцию addTrailingZeroIfNeeded

2021-06-20 11:58 UTC, dtsaryov commented on js/main.js
> +  const typesPremise = ['palace', 'flat', 'house', 'bungalow', 'hotel'];
offerTypes

2021-06-20 11:58 UTC, dtsaryov commented on js/main.js
> +    return typesCheckin[getRandomInt(0, typesCheckin.length - 1)];
В куче мест один и тот же код - выбор случайного элемента из массива - это повод сделать утилитную функцию для этого

2021-06-20 11:58 UTC, dtsaryov commented on js/main.js
> +  const ads = {};
Объявляй переменную максимально близко к её использованию.

Нет смысла создавать объект тут, когда по факту он используется в самом конце

2021-06-20 11:58 UTC, dtsaryov commented on js/main.js
> +  }
Перепиши с использованием slice и функции перемешивания:

```JS
function shuffle(array) {
  return array.slice().sort(function () { return Math.random() - 0.5; });
};
```

2021-06-20 11:58 UTC, dtsaryov commented on js/main.js
> +    return outPhotos;
Для этого есть функция slice

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/slice

2021-06-20 11:58 UTC, dtsaryov commented on js/main.js
> +    lng: getRandomFloat(139.70000, 139.80000, 5),
[Д19. В коде не используются «магические значения», под каждое из них заведена отдельная переменная, названная как константа.](https://up.htmlacademy.ru/javascript/23/criteries#d19)

2021-06-20 11:58 UTC, dtsaryov commented on js/main.js
> +    price: getRandomInt(0, 9007199254740992),
[Д19. В коде не используются «магические значения», под каждое из них заведена отдельная переменная, названная как константа.](https://up.htmlacademy.ru/javascript/23/criteries#d19)

2021-06-20 11:58 UTC, dtsaryov commented on js/main.js
> +    guests: getRandomInt(0, 9007199254740992),
[Д19. В коде не используются «магические значения», под каждое из них заведена отдельная переменная, названная как константа.](https://up.htmlacademy.ru/javascript/23/criteries#d19)

2021-06-20 11:58 UTC, dtsaryov commented on js/main.js
> +for (let i = 0; i < 10; i++) {
[Д19. В коде не используются «магические значения», под каждое из них заведена отдельная переменная, названная как константа.](https://up.htmlacademy.ru/javascript/23/criteries#d19)

2021-06-23 21:40 UTC, dtsaryov requested changes
Внимательно перечитай задание, ТЗ, обращай внимание на критерии и не забывай запускать ESLint перед отправкой задания

<img width="842" alt="Screen Shot 2021-06-24 at 12 39 58 AM" src="https://user-images.githubusercontent.com/6183810/123171616-ba38fa80-d484-11eb-8f8c-fae0c05de8cb.png">

2021-06-23 21:40 UTC, dtsaryov commented on js/main.js
> +const TYPES_CHECKOUT = ['12:00', '13:00', '14:00'];
Не стоит 2 раза хранить одно и то же

2021-06-23 21:40 UTC, dtsaryov commented on js/main.js
> +const avatarLinks = [];
не нужен массив под аватары - просто сделай сделай функцию `addLeadingZeroIfNeeded`, которая будет добавлять ведущий ноль, если число меньше 10 и оберни вызов генерации случайного числа:

```JS
{
  // ...
  avatar: `img/avatars/user${addLeadingZeroIfNeeded(getRandomInt(0, 10)).png`
}

2021-06-23 21:40 UTC, dtsaryov commented on js/main.js
> +const allAds = [];
Этот массив перед самой генерацией стоит объявлять

2021-06-23 21:40 UTC, dtsaryov commented on js/main.js
> +}
Забей на уникальность

2021-06-23 21:40 UTC, dtsaryov commented on js/main.js
> +  return array.slice().sort(() => Math.random() -0.5);
Давай если уж тут стали использовать стрелочную функцию, то везде их будем использовать

2021-06-23 21:40 UTC, dtsaryov commented on js/main.js
> +}
Чет тоже какая-то заморочка. Просто сортируй через shuffleArray и выбирай случайный кусок с помощью slice

2021-06-23 21:40 UTC, dtsaryov commented on js/main.js
> +  const LNG = getRandomFloat(139.70000, 139.80000, 5);
Эти граничные значения широты и долготы нужно в константы вынести

2021-06-23 21:40 UTC, dtsaryov commented on js/main.js
> +  const FEATURES = getShuffleArray(TYPES_FEATURES);
Во-первых, это не константы, а неизменяемые переменные, а значит именуются в lowerCamelCase.
Во-вторых, если ты переменную используешь только один раз, то если выражение, вычисляющее ее, простое, то можно его подставить туда, где используется переменная:

```JS
offer: {
  price: getRandomInt(0, 500000),
  // ...
}

2021-06-23 21:40 UTC, dtsaryov commented on js/main.js
> +      address: [LAT, LNG],
address - это строка, а не массив

2021-06-23 21:40 UTC, dtsaryov commented on js/main.js
> +function getShuffleArray(array){
либо getShuffledArray, либо shuffleArray

2021-06-23 21:40 UTC, dtsaryov commented on js/main.js
> +for (let i = 0; i < 10; i++) {
Ну и давай в одну строку:

```JS
const offers = new Array(OFFERS_COUNT).fill(null).map(generateOffer);

2021-06-23 21:40 UTC, dtsaryov commented on js/main.js
> +function createAds() {
Во-первых, функция возвращает один объект, а называется так, как будто несколько.

Во-вторых, давай лучше использовать слово "offer" - `generateOffer`

2021-06-24 17:50 UTC, Akame320 commented
А почему Eslint выдает ошибку в функции getShuffledArray. Где мы вызываем sort() и передаем в его параметр callback функцию. Которая вовзращает разность генерируемого рандомного числа и 5?

2021-06-25 12:27 UTC, dtsaryov requested changes

2021-06-25 12:27 UTC, dtsaryov commented on js/main.js
> +const offers = new Array(10).fill(null).map(generateOffer);
напиши над этой строкой, чтобы ESLint не ругался:

`// eslint-disable-next-line no-unused-vars`

2021-06-25 12:27 UTC, dtsaryov commented on js/main.js
> +const getRandomFloat = (minNumber, maxNumber, precision = -1) => {
Ну а все остальные функции-то чего на стрелочные не поменял?

2021-06-25 12:32 UTC, dtsaryov requested changes

2021-06-25 12:32 UTC, dtsaryov commented on js/main.js
> +}
```JS
const addLeadingZeroIfNeeded = (number) => number < 10 ? `0${number}` : `${number}`;
```

2021-06-25 12:32 UTC, dtsaryov commented on js/main.js
> +}
Сделай строчной функцией

2021-06-25 12:32 UTC, dtsaryov commented on js/main.js
> +function getShuffledArray(array) {
Сделай строчной функцией

2021-06-25 12:32 UTC, dtsaryov commented on js/main.js
> +  return array.slice().sort(function () { return Math.random() - 0.5; });
`array.slice().sort(() => Math.random() - 0.5)`

2021-06-25 12:32 UTC, dtsaryov commented on js/main.js
> +function generateOffer() {
Сделай строчной функцией

2021-06-26 14:26 UTC, dtsaryov approved these changes

2021-06-26 14:26 UTC, merged